export enum UserActionTypes {
    LOAD_USERS = "LOAD_USERS",
    LOAD_USERS_ERROR = "LOAD_USERS_ERROR",
    LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS"
}

export enum TodosActionTypes {
    LOAD_TODOS = "LOAD_TODOS",
    LOAD_TODOS_ERROR = "LOAD_TODOS_ERROR",
    LOAD_TODOS_SUCCESS = "LOAD_TODOS_SUCCESS",
    SET_PAGE = "SET_PAGE",
}
